import { Layout } from "~/components/layout";
import { type NextPage } from "next";
import Head from "next/head";
import { FsTreeView } from "~/components/fs-treeview";
("use client");

const FirstSteps: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>First Steps</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Eu sou um{" "}
            <span className="text-[hsl(280,100%,70%)]">exemplinho</span>!
          </h1>
          <FsTreeView />
        </div>
      </main>
    </Layout>
  );
};
export default FirstSteps;
