import { type NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import { Layout } from "~/components/layout";
import { Button } from "~/components/ui/button";
import Head from "next/head";

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl ">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      {sessionData ? (
        <Button onClick={() => void signOut({ callbackUrl: "/" })}>
          {"Sign Out"}
        </Button>
      ) : (
        ""
      )}
    </div>
  );
};

const Foo: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Foo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Oiiiiii <span className="text-[hsl(280,100%,70%)]">MUNDO</span>!
          </h1>
          <AuthShowcase />
        </div>
      </main>
    </Layout>
  );
};

export default Foo;
