import { type NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { Layout } from '~/components/layout';
import { api } from '~/utils/api';

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={
          sessionData
            ? () => void signOut()
            : () => void signIn(undefined, { callbackUrl: '/workboard' })
        }
      >
        {sessionData ? 'Sign out' : 'Sign in'}
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>DeepSirius UI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Deep</span>Sirius
          </h1>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <a
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              target="_blank"
              rel="noopener noreferrer"
              href="https://deepsirius-ui-docs.vercel.app/"
            >
              <h3 className="text-2xl font-bold">Quick Start →</h3>
              <div className="text-lg">Just the basics.</div>
            </a>
            <a
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              target="_blank"
              rel="noopener noreferrer"
              href="https://deepsirius-ui-docs.vercel.app/user"
            >
              <h3 className="text-2xl font-bold">User Guide →</h3>
              <div className="text-lg">Learn more about DeepSirius.</div>
            </a>
          </div>
          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
