import { ArrowRightIcon } from 'lucide-react';
import { type NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { Layout } from '~/components/layout';

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <div className="flex gap-4">
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={
            sessionData
              ? () => void signOut()
              : () => void signIn(undefined, { callbackUrl: '/workboard' })
          }
        >
          {sessionData ? 'Sign out' : 'Sign in'}
        </button>
        {sessionData && (
          <Link
            href="/workboard"
            className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          >
            <span>Workboard</span>
            <ArrowRightIcon className="ml-2 inline-block w-5 h-5 text-white" />
          </Link>
        )}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>DeepSirius UI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Deep</span>Sirius
          </h1>
          <AuthShowcase />
        </div>
      </main>
    </Layout>
  );
};

export default Home;
